services:
  database:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - 47474:7474
      - 47687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
